### ISSUE TITLE
https://hoa.moe/问题

### ISSUE THREAD

**Issue by phychi** [HITSZ-OpenAuto/hitsz-openauto.github.io#10]
无法点进docx格式文件 
<img width="595" alt="屏幕截图 2023-11-16 144215" src="https://github.com/HITSZ-OpenAuto/HITSZ-OpenAuto/assets/102468424/7346b12d-6606-48f4-8d71-09e4e7f5a4bd">

**Comment by xiln7** [comment]
> 无法点进docx格式文件 <img alt="屏幕截图 2023-11-16 144215" width="595" src="https://user-images.githubusercontent.com/102468424/283344695-7346b12d-6606-48f4-8d71-09e4e7f5a4bd.png">

已经修复
